spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1783247180/spring-cloud-starter     # 配置git仓库的地址
          search-paths: config-repo
          username: 1783247180                                             # git仓库的账号
          password: qq19991015*.
server:
  port: 12000